# -----------------------------------------------------------------------------
#  Step 8: make `lidar` an installable package.
#
#  Everything up to now has been usable only from inside this build tree. This
#  file makes `find_package(lidar)` work in a completely separate project that
#  has never heard of auv_middleware.
# -----------------------------------------------------------------------------

include(GNUInstallDirs)              # CMAKE_INSTALL_LIBDIR, _INCLUDEDIR, _BINDIR
include(CMakePackageConfigHelpers)   # configure_package_config_file, version file

# -- the library itself ------------------------------------------------------
# EXPORT lidarTargets records this target in a named set; install(EXPORT ...)
# below turns that set into a .cmake file the consumer can include.
install(TARGETS lidar
  EXPORT  lidarTargets
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)

# -- the public headers ------------------------------------------------------
# Only include/lidar. include/mw is deliberately left behind: mw is an
# implementation detail that lives inside liblidar.so, and a consumer of this
# package must never be able to include mw/transport.hpp.
install(DIRECTORY ${PROJECT_SOURCE_DIR}/include/lidar
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
  FILES_MATCHING PATTERN "*.hpp"
)

# -- the target description --------------------------------------------------
# Writes lidarTargets.cmake: an add_library(lidar::lidar SHARED IMPORTED)
# plus the absolute paths and interface properties, generated by CMake rather
# than written by hand.
install(EXPORT lidarTargets
  FILE        lidarTargets.cmake
  NAMESPACE   lidar::
  DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/lidar
)

# -- version compatibility ---------------------------------------------------
# SameMinorVersion, not SameMajorVersion, because we are pre-1.0: at 0.x the
# minor number is where breaking changes live, so 0.1 must not satisfy a
# request for 0.2.
write_basic_package_version_file(
  ${CMAKE_CURRENT_BINARY_DIR}/lidarConfigVersion.cmake
  VERSION       ${PROJECT_VERSION}
  COMPATIBILITY SameMinorVersion
)

# -- the entry point find_package() looks for --------------------------------
configure_package_config_file(
  ${PROJECT_SOURCE_DIR}/cmake/lidarConfig.cmake.in
  ${CMAKE_CURRENT_BINARY_DIR}/lidarConfig.cmake
  INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/lidar
)

install(FILES
  ${CMAKE_CURRENT_BINARY_DIR}/lidarConfig.cmake
  ${CMAKE_CURRENT_BINARY_DIR}/lidarConfigVersion.cmake
  DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/lidar
)